### ISSUE TITLE
使用msgpack序列化json

### ISSUE THREAD

**Issue by i5ting** [moajs/moa-api#4]
http://msgpack.org/

**Comment by i5ting** [comment]
可配置，默认不开启

**Comment by leapon** [comment]
https://github.com/mcollina/msgpack5

**Comment by i5ting** [comment]
create a pr

**Comment by leapon** [comment]
老大，encode／decode 直接用 msgpack5 就好了。这个 issue 太笼统，不是所有的json都需要msgpack压一下。

**Comment by i5ting** [comment]
做成一个配置项，如果默认压缩json，那么用户是感觉不到我们用了msgpack的，所有的api也都不要他自己处理
