### ISSUE TITLE
关于require('mount-controllers')加载类的问题

### ISSUE THREAD

**Issue by jameBoy** [moajs/moa-api#5]
var $middlewares  = require('mount-middlewares')(__dirname);

// core controller
var $ = require('mount-controllers')(__dirname).users_controller;

这里的require('mount-controllers')(__dirname)和 require('mount-middlewares')(__dirname);是什么样的用法？

**Comment by i5ting** [comment]
hi

require('mount-controllers')(__dirname)会加载当前目录下的app/controllers下的所有文件，

比如users_controller.js

那么它就是

```
var $ = require('mount-controllers')(__dirname).users_controller;
```

这样可以少些一些代码，另外对生成器会非常友好
